BoozeHoundCloud/Areas/Core/Controllers/TransactionController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using BoozeHoundCloud.Areas.Core.Models;
using BoozeHoundCloud.Areas.Core.Services;
using BoozeHoundCloud.Areas.Core.ViewModels;
using BoozeHoundCloud.Models;

namespace BoozeHoundCloud.Areas.Core.Controllers
{
  public class TransactionController : Controller
  {
    //-------------------------------------------------------------------------

    private readonly IApplicationDbContext _context;
    private readonly IUserService _userService;
    private readonly ITransactionService _transactionService;
    private readonly IAccountService _accountService;

    //-------------------------------------------------------------------------

    public TransactionController()
    {
      _context = new ApplicationDbContext();
      _userService = new UserService(_context);
      _transactionService = TransactionService.Create(_context);
      _accountService = AccountService.Create(_context);
    }

    //-------------------------------------------------------------------------

    // Core/Transaction
    [HttpGet]
    public ActionResult Index()
    {
      return View();
    }

    //-------------------------------------------------------------------------

    // Core/Transaction/New
    [HttpGet]
    public ActionResult New()
    {
      var viewModel = new TransactionFormViewModel
      {
        Date = DateTime.UtcNow,
        Accounts = _accountService.GetAll(_userService.CurrentUserId).ToList()
      };

      return View("TransactionForm", viewModel);
    }

    //-------------------------------------------------------------------------

    // Core/Transaction/Edit
    [HttpGet]
    public ActionResult Edit(int id)
    {
      Transaction transaction = _transactionService.GetTransaction(id);

      if (transaction == null)
      {
        return HttpNotFound();
      }

      var viewModel = new TransactionFormViewModel
      {
        Id = transaction.Id,
        Value = transaction.Value,
        DebitAccountId = transaction.DebitAccountId,
        DebitAccount = transaction.DebitAccount,
        CreditAccountId = transaction.CreditAccountId,
        CreditAccount = transaction.CreditAccount,
        Accounts = _accountService.GetAll(_userService.CurrentUserId).ToList(),
        Reference = transaction.Reference,
        Description = transaction.Description,
        Date = transaction.Date,
        CreatedTimestamp = transaction.CreatedTimestamp,
        ProcessedTimestamp = transaction.ProcessedTimestamp
      };

      return View("TransactionForm", viewModel);
    }

    //-------------------------------------------------------------------------

    // Core/Transaction/Save
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Save(Transaction transaction)
    {
      if (ModelState.IsValid == false)
      {
        return Edit(transaction.Id);
      }

      bool isNewTransaction = (transaction.Id == 0);

      if (isNewTransaction)
      {
        _transactionService.AddTransaction(transaction);
      }
      else
      {
        _transactionService.UpdateTransaction(transaction);
      }
      
      return RedirectToAction("Index");
    }

    //-------------------------------------------------------------------------
  }
}

BoozeHoundCloud/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Booze Hound Cloud</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Booze Hound Cloud", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Accounts", "Index", "Account", new { Area = "Core" }, new {})</li>
                <li>@Html.ActionLink("Transactions", "Index", "Transaction", new { Area = "Core" }, new {})</li>
                @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
              </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Booze Hound Cloud</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>